sudo: required
services:
  - docker
language: go
jobs:
  include:
    - stage: get
      script: go get -u
    - stage: test
      script: go get github.com/stretchr/testify
      script: go test -v -race
    - stage: push
      script: make push
go:
  - 1.x
