sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
language: go
jobs:
  include:
    - stage: test
      script: go test -v -race
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
go:
  - 1.x
