sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
language: go
jobs:
  include:
    - stage: test
      script: go test -v -race
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - apt-get install ruby ruby-dev rubygems build-essential
  - gem install --no-ri --no-rdoc fpm
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
go:
  - 1.x
