sudo: required
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
language: go
jobs:
  include:
    - stage: test
      script: go test -v -race
    - stage: deploy
      script: test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
go:
  - 1.x
