sudo: required
services:
  - docker
before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes gcc-multilib > /dev/null; fi
  - sudo apt-get install -y build-essential rpm
  - gem install --no-ri --no-rdoc fpm
addons:
  apt:
    packages:
      - docker-ce
language: go
jobs:
  include:
    - stage: test
      script: make test
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
go:
  - 1.x
